### ISSUE TITLE
From sealedbox to AE

### ISSUE THREAD

**Issue by DeveloppSoft** [quininer/sarkara#9]
Hi @quininer,

Was playing with `sarkara::sealedbox` as of today and found me struggling with a small problem, my goal is to extract the `AeadCipher` out of the `Opening<AE>` or `Sealing<AE>` objects, however I am simply failing. Am I supposed to do it in a precise way?

Tried the dumb way of `sealedbox_instance.0` but it tells me `0` is a private field, experiencing with implementing a custom trait at the moment.

**Comment by quininer** [comment]
Under normal circumstances you should not do this.

You can implement a MySealedBox yourself using KEX, AE.

**Comment by DeveloppSoft** [comment]
Ok, will do so then.
Any explanations why so?

**Comment by quininer** [comment]
SealedBox should have a clear behavior to prevent `SealedBox::recv().encrypt(..)`.

**Comment by DeveloppSoft** [comment]
Ok thanks, closing this then.
